CREATE TABLE IF NOT EXISTS films
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255),
    description varchar(200),
    releaseDate date,
    duration    bigint,
    mpa_Id      bigint
    );

CREATE TABLE IF NOT EXISTS likes
(
    film_id bigint,
    user_id bigint
);

CREATE TABLE IF NOT EXISTS mpa_type
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
    );

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  bigint,
    genre_id bigint,
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS genre_type
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
    );

CREATE TABLE IF NOT EXISTS users
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(255),
    login    varchar(255),
    name     varchar(255),
    birthday date
    );

CREATE TABLE IF NOT EXISTS friends
(
    user_id   bigint,
    friend_id bigint,
    PRIMARY KEY (user_id, friend_id)
    );